CREATE TABLE IF NOT EXISTS SB1010 (
    SB1COD INT PRIMARY KEY AUTO_INCREMENT,
    SB1NOME VARCHAR(50) NOT NULL,
    SB1DESC TEXT NOT NULL,
    SB1CATE VARCHAR(30) NOT NULL,
    SB1PESO FLOAT(5, 2) NOT NULL,
    SB1VALOR DECIMAL(5 ,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS Z11010 (
    Z11COD INT PRIMARY KEY AUTO_INCREMENT,
    Z11NUMPROC VARCHAR(50) NOT NULL,
    Z11NOMEINT VARCHAR(100) NOT NULL,
    Z11NOMEADV VARCHAR(100) NOT NULL,
    Z11NOMETRI VARCHAR(100) NOT NULL,
    Z11DESC TEXT NOT NULL
);
